const LEGAL_RESEARCH_SUCCESS_PROXIES = 'Legal research success proxies';
const SEARCH_EVENTS = 'Search events';
const DEFAULT_EVENT_VALUE = 0;

export {
  LEGAL_RESEARCH_SUCCESS_PROXIES,
  SEARCH_EVENTS,
  DEFAULT_EVENT_VALUE,
};